apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qbkrsaqzy-go
  janus-idp.io/tekton: qbkrsaqzy-go
  backstage.io/kubernetes-id: qbkrsaqzy-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qbkrsaqzy-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
